import 'package:instagram/core/mock_data/home.mock.data.dart';
import 'package:instagram/core/models/reel.model.dart';

final List<Reel> reels = [
  Reel(
    postedBy: currentUser,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'Magic',
    caption: 'caption',
    totalLikes: '20 K',
    totalComments: '10 K',
    isLiked: true,
    isTagged: false,
    taggedUser: mockUser,
  ),
  Reel(
    postedBy: mockUser,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'xxx',
    caption: 'caption',
    totalLikes: '5k',
    totalComments: '10 M',
    isLiked: true,
    isTagged: false,
    taggedUser: mockUser2,
  ),
  Reel(
    postedBy: mockUser3,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'DD',
    caption: 'Lsafjindsjfsdbfhjib h bhb udibauisdbuoib ibsdb ai oipoi ba sd',
    totalLikes: '50 K',
    totalComments: '10 M',
    isLiked: false,
    isTagged: false,
    taggedUser: mockUser5,
  ),
  Reel(
    postedBy: mockUser4,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'Defi ',
    caption: 'Lsafjindsjfsdbfhjib h bhb udibauisdbuoib ibsdb ai oipoi ba sd',
    totalLikes: '5k',
    totalComments: '10 K',
    isLiked: true,
    isTagged: false,
    taggedUser: mockUser2,
  ),
  Reel(
    postedBy: mockUser5,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'Magic',
    caption: 'Lsafjindsjfsdbfhjib h bhb udibauisdbuoib ibsdb ai oipoi ba sd',
    totalLikes: '5k',
    totalComments: '10 K',
    isLiked: false,
    isTagged: true,
    taggedUser: mockUser,
  ),
  Reel(
    postedBy: currentUser,
    imgUrl: currentUser.profilePhoto,
    audioTitle: 'Magic',
    caption: 'Lsafjindsjfsdbfhjib h bhb udibauisdbuoib ibsdb ai oipoi ba sd',
    totalLikes: '5000 K',
    totalComments: '10 K',
    isLiked: true,
    isTagged: true,
    taggedUser: mockUser,
  ),
];
